# Generated by Django 5.1.5 on 2025-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_publications',
            field=models.IntegerField(default=0, verbose_name='Количество публикаций'),
        ),
    ]
