# Generated by Django 5.1.5 on 2025-02-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_publication_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='auther',
            new_name='author',
        ),
    ]
