# Generated by Django 5.1.5 on 2025-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_auther_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='comments_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик комментариев'),
        ),
        migrations.AddField(
            model_name='publication',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик лайков'),
        ),
    ]
