# Generated by Django 5.1.5 on 2025-02-05 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_publication_created_at_publication_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='users_liked',
            field=models.ManyToManyField(related_name='favorite_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
